### ISSUE TITLE
Pre-battle screen incorrectly reports number of leader cards that can be removed

### ISSUE THREAD

**Issue by Salvatos** [Democide/nowhere-prophet-bugs#10]
**Describe the bug**
If you have a level up pending, the pre-battle screen incorrectly reports your number of leader cards that can be removed (I forget what the points are called). e.g. if you have 0 point and enough XP to level up once, the interface will show that you can remove 1 card. See screenshots below.

**To reproduce**
1. Earn enough XP to level up, but do not proceed to level up.
2. Start battle.
3. Look under leader deck edit button.

**Expected behavior**
The number of "removal" points should be based on the actual, not theoretical, points available.

**Screenshots**
https://imgur.com/a/VWWXIh3

**Comment by Democide** [comment]
It actually shows the number of level-ups you have. But showing focus points would be superb too! I'll put it on my list of improvements!
