### ISSUE TITLE
Autocannon not working properly

### ISSUE THREAD

**Issue by MMoserM** [Democide/nowhere-prophet-bugs#2]
When the enemy ended the turn, the Autocannon should have blasted my Blackscale Ghram.
![image](https://user-images.githubusercontent.com/15054621/58189380-c7290580-7c90-11e9-9281-92afdd0c2ffe.png)
![image](https://user-images.githubusercontent.com/15054621/58189415-d740e500-7c90-11e9-8bf4-e22de9a3df10.png)

**Comment by Democide** [comment]
Alright. Something is super weird there. The autocannon does not look like that. Not for a long time. In fact, leader cards are PURPLE, not RED right now - have been for a few months. Are you, possibly, playing a REALLY OLD version?

**Comment by MMoserM** [comment]
Sorry took some old messages from th bug report i will look to only add the ones after last friday

**Comment by Democide** [comment]
That probably makes sense. I'll close this then.
