### ISSUE TITLE
Feral Warchief retreated, and the picture shows Blue Devils (Lepers) 

### ISSUE THREAD

**Issue by MMoserM** [Democide/nowhere-prophet-bugs#3]
![image](https://user-images.githubusercontent.com/15054621/58189536-0bb4a100-7c91-11e9-9187-16c717c3386c.png)

 This happens in a fight where you save some Blue Devils from an attack.    This is the follow up shot. 
![image](https://user-images.githubusercontent.com/15054621/58189556-166f3600-7c91-11e9-8e70-a259845f76a3.png)

**Comment by MMoserM** [comment]
Maybe this is just a typical "run away" picture.

**Comment by Democide** [comment]
This looks like I have fixed it. Is this an old report?

**Comment by MMoserM** [comment]
Yes
