### ISSUE TITLE
Unshakable wording issue

### ISSUE THREAD

**Issue by MMoserM** [Democide/nowhere-prophet-bugs#5]
Its a little weird how it says "Permanent" at the end. 
![image](https://user-images.githubusercontent.com/15054621/58189881-b3ca6a00-7c91-11e9-8609-e25d39d8e0ef.png)

**Comment by Democide** [comment]
This also seems like an old issue. there is a Period at the end of that sentence now, and I think Permanent is no longer shown if the buff has no duration (not sure about that tho). Still the period should fix things, unless there is some issue there.
